# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1018, 794)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.dashboard_navigator = QtWidgets.QTabWidget(self.centralwidget)
        self.dashboard_navigator.setGeometry(QtCore.QRect(10, 0, 1001, 761))
        self.dashboard_navigator.setObjectName("dashboard_navigator")
        self.hand_symbol_recognition = QtWidgets.QWidget()
        self.hand_symbol_recognition.setObjectName("hand_symbol_recognition")
        self.dashboard_navigator.addTab(self.hand_symbol_recognition, "")
        self.ocr = QtWidgets.QWidget()
        self.ocr.setObjectName("ocr")
        self.dashboard_navigator.addTab(self.ocr, "")
        self.image_captioning = QtWidgets.QWidget()
        self.image_captioning.setObjectName("image_captioning")
        self.dashboard_navigator.addTab(self.image_captioning, "")
        self.text_to_speech = QtWidgets.QWidget()
        self.text_to_speech.setObjectName("text_to_speech")
        self.dashboard_navigator.addTab(self.text_to_speech, "")
        self.speech_to_text = QtWidgets.QWidget()
        self.speech_to_text.setObjectName("speech_to_text")
        self.dashboard_navigator.addTab(self.speech_to_text, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionhello = QtWidgets.QAction(MainWindow)
        self.actionhello.setObjectName("actionhello")

        self.retranslateUi(MainWindow)
        self.dashboard_navigator.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.dashboard_navigator.setTabText(self.dashboard_navigator.indexOf(self.hand_symbol_recognition), _translate("MainWindow", "Tab 1"))
        self.dashboard_navigator.setTabText(self.dashboard_navigator.indexOf(self.ocr), _translate("MainWindow", "Tab 2"))
        self.dashboard_navigator.setTabText(self.dashboard_navigator.indexOf(self.image_captioning), _translate("MainWindow", "Page"))
        self.dashboard_navigator.setTabText(self.dashboard_navigator.indexOf(self.text_to_speech), _translate("MainWindow", "Page"))
        self.dashboard_navigator.setTabText(self.dashboard_navigator.indexOf(self.speech_to_text), _translate("MainWindow", "Page"))
        self.actionhello.setText(_translate("MainWindow", "hello"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
